access_log off;
log_format production escape=none '
[$time_iso8601] [$remote_addr@$remote_user] $http_user_agent
"$request" |> [$status:$body_bytes_sent]
"$http_referer" |> "$http_x_forwarded_for"';

server {
    gzip on;
    listen 8080;

    location / {
        root /opt/app;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ^~ /api/ {
        proxy_pass http://api/;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Host $http_host;
        proxy_set_header Host $host;

        proxy_cache_bypass $http_upgrade;
        proxy_ssl_session_reuse off;
        proxy_pass_header Server;
        proxy_redirect off;
    }

    access_log  /var/log/nginx/access.log  production;
    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
