access_log off;
log_format dev escape=none '
[$time_iso8601] [$remote_addr@$remote_user] $http_user_agent
"$request" |> [$status:$body_bytes_sent]
"$http_referer" |> "$http_x_forwarded_for"';

server {
    listen 8080;

    location / {
        proxy_pass http://web:8080;
        proxy_pass_header Server;
        proxy_redirect off;
    }

    location ^~ /api/ {
        proxy_pass http://api:8080/;
        proxy_pass_header Server;
        proxy_redirect off;
    }

    access_log  /var/log/nginx/access.log dev;
}
