error_log /var/log/nginx/global-error.log debug;
access_log /var/log/nginx/global-access.log;
log_format production escape=none '
[$time_iso8601] [$remote_addr@$remote_user] $http_user_agent
"$request" |> [$status:$body_bytes_sent]
"$http_referer" |> "$http_x_forwarded_for"';

server {
    gzip on;
    listen 8080;

    location ^~ /api/ {
        proxy_ssl_server_name on;
        proxy_pass_header Server;
        proxy_pass http://api:8080/;
        proxy_redirect off;
    }

    location / {
        root /opt/app;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    access_log /var/log/nginx/global-access.log production;
    error_log /var/log/nginx/global-error.log debug;
    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
