const defaultTheme = require( 'tailwindcss/defaultTheme' );
const plugin = require( 'tailwindcss/plugin' );

const variants = [
    'responsive',
    // 'dark',
    // 'motion-safe',
    // 'motion-reduce',
    // 'first',
    // 'last',
    // 'odd',
    // 'even',
    'visited',
    'checked',
    // 'group-hover',
    // 'group-focus',
    // 'focus-within',
    'hover',
    'focus',
    // 'focus-visible',
    'active',
    'disabled',

    // '+checked',
    // '+blank',
    // '+empty',
    '+focus',
];

module.exports = {
    future: {
        removeDeprecatedGapUtilities: true,
        purgeLayersByDefault: true,
        standardFontWeights: true,
    },
    purge: [
        './public/**/*.html',
        './src/**/*.vue',
    ],
    theme: {
        extend: {},
        fontFamily: {
            sans: [ 'Inter', ...defaultTheme.fontFamily.sans ],
        },
    },
    plugins: [
        // plugin( ( { addVariant, e } ) =>
        //     addVariant( '+checked', ( { modifySelectors, separator } ) =>
        //         modifySelectors( ( { className } ) =>
        //             `:checked + .${ e( `+checked${ separator }${ className }` ) }`,
        //         ),
        //     ),
        // ),
        // plugin( ( { addVariant, e } ) =>
        //     addVariant( '+blank', ( { modifySelectors, separator } ) =>
        //         modifySelectors( ( { className } ) =>
        //             `:blank + .${ e( `+blank${ separator }${ className }` ) }`,
        //         ),
        //     ),
        // ),
        // plugin( ( { addVariant, e } ) =>
        //     addVariant( '+empty', ( { modifySelectors, separator } ) =>
        //         modifySelectors( ( { className } ) =>
        //             `:empty + .${ e( `+empty${ separator }${ className }` ) }`,
        //         ),
        //     ),
        // ),
        plugin( ( { addVariant, e } ) =>
            addVariant( '+focus', ( { modifySelectors, separator } ) =>
                modifySelectors( ( { className } ) =>
                    `:focus + .${ e( `+focus${ separator }${ className }` ) }` ),
            ),
        ),
    ],
    variants: {
        accessibility: variants,
        alignContent: variants,
        alignItems: variants,
        alignSelf: variants,
        appearance: variants,
        backgroundAttachment: variants,
        backgroundClip: variants,
        backgroundColor: variants,
        backgroundImage: variants,
        gradientColorStops: variants,
        backgroundOpacity: variants,
        backgroundPosition: variants,
        backgroundRepeat: variants,
        backgroundSize: variants,
        borderCollapse: variants,
        borderColor: variants,
        borderOpacity: variants,
        borderRadius: variants,
        borderStyle: variants,
        borderWidth: variants,
        boxShadow: variants,
        boxSizing: variants,
        container: variants,
        cursor: variants,
        display: variants,
        divideColor: variants,
        divideOpacity: variants,
        divideStyle: variants,
        divideWidth: variants,
        fill: variants,
        flex: variants,
        flexDirection: variants,
        flexGrow: variants,
        flexShrink: variants,
        flexWrap: variants,
        float: variants,
        clear: variants,
        fontFamily: variants,
        fontSize: variants,
        fontSmoothing: variants,
        fontVariantNumeric: variants,
        fontStyle: variants,
        fontWeight: variants,
        height: variants,
        inset: variants,
        justifyContent: variants,
        justifyItems: variants,
        justifySelf: variants,
        letterSpacing: variants,
        lineHeight: variants,
        listStylePosition: variants,
        listStyleType: variants,
        margin: variants,
        maxHeight: variants,
        maxWidth: variants,
        minHeight: variants,
        minWidth: variants,
        objectFit: variants,
        objectPosition: variants,
        opacity: variants,
        order: variants,
        outline: variants,
        overflow: variants,
        overscrollBehavior: variants,
        padding: variants,
        placeContent: variants,
        placeItems: variants,
        placeSelf: variants,
        placeholderColor: variants,
        placeholderOpacity: variants,
        pointerEvents: variants,
        position: variants,
        resize: variants,
        space: variants,
        stroke: variants,
        strokeWidth: variants,
        tableLayout: variants,
        textAlign: variants,
        textColor: variants,
        textOpacity: variants,
        textDecoration: variants,
        textTransform: variants,
        userSelect: variants,
        verticalAlign: variants,
        visibility: variants,
        whitespace: variants,
        width: variants,
        wordBreak: variants,
        zIndex: variants,
        gap: variants,
        gridAutoFlow: variants,
        gridTemplateColumns: variants,
        gridAutoColumns: variants,
        gridColumn: variants,
        gridColumnStart: variants,
        gridColumnEnd: variants,
        gridTemplateRows: variants,
        gridAutoRows: variants,
        gridRow: variants,
        gridRowStart: variants,
        gridRowEnd: variants,
        transform: variants,
        transformOrigin: variants,
        scale: variants,
        rotate: variants,
        translate: variants,
        skew: variants,
        transitionProperty: variants,
        transitionTimingFunction: variants,
        transitionDuration: variants,
        transitionDelay: variants,
        animation: variants,
    },
};
